- name: install nginx 
  hosts: web
  become: yes # take sudo access
  tasks: 
    - name: install nginx
      ansible.builtin.package: #to install packages
        name: nginx
        state: present
    
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes