- name: variables to print
  hosts: web
  vars: # play level,all tasks in this play have access to use this
    COURSE: "aws devops"
    DURATION: "3 months"
    TRAINER: "shiva"
  tasks: 
    - name: print info
      ansible.builtin.debug:
        msg: "iam preparing: {{COURSE}}, duration: {{DURATION}}, trainer: {{TRAINER}} shive"
