- name: print info on the promt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: "please enter course details"
    private: false # not confidential
  - name: DURATION
    prompt: "please enter duration"
    private: false # not confidential
  - name: TRAINER
    prompt: "please enter trainer details"
    private: false # not confidential
  tasks:
  - name: print the course details
    ansible.builtin.debug:
      msg: "Hi, Iam learning: {{COURSE}}, DURATION IS {{DURATION}}, trainer is: {{TRAINER}}"