- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"
    
  - name: to convert to upper case
    vars: 
      greetings: "hello Devops"
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

  - name: conver to lowercase
    vars:
      greetings: "hi devops TEAM"
    ansible.builtin.debug:
      msg: "{{ greetings | lower }}"

  - name: conver to lowercase
    vars:
      number: [1,2,2,2,2,2,4,5,7,3,2,3,7,9]
    ansible.builtin.debug:
      msg: "{{ number | unique }}"

  - name: list to map
    vars:
      course:
        name: "devops"
        trainer: "shiva"
        duration: 120
    ansible.builtin.dubug:
      msg: " {{ course | dict2items }} "