- name: create ec2 and R53
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-056d250186c3df687"
    sg_id: "sg-0dcb81243a4d41417"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: hawsdevops.online
  tasks: 
  - name: ansible to install pip boto3
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: " {{ subnet_id }} "
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instance

  - name: print ec2 instance
    ansible.builtin.debug:
      msg: "{{ ec2_instance }}"

  - name: create r53 private record
    amazon.aws.route53:
      state: present:
      zone: "{{ zone}}"
      record: " {{ item.item }}.{{ zone }} "
      type: a
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
      loop: "{{ ec2_instances.results }}"

